### ISSUE TITLE
When framer motion animation starts content shifting in small and medium devices ?

### ISSUE THREAD

**Issue by BasirKhan418** [BasirKhan418/Project-Studio#1]
When framer motion animation starts in whileinview the content shifting in x axis small and medium devices  and i don't know why? In the 15inch or 14 inch screen its working great but in mobile phone screen the animation when starts the content shifted in x axis ?

**Comment by tusharkc** [comment]
Yeah, I can replicate this issue. I have forked the project, I will submit the PR soon.

**Comment by BasirKhan418** [comment]
Sounds good. Nice to here from you. I will be waiting for your PR.

**Comment by BasirKhan418** [comment]
Issue resolved Thanks tusharkc
