### ISSUE TITLE
Add CONTRIBUTION.md file 

### ISSUE THREAD

**Issue by Abhineshhh** [BasirKhan418/Project-Studio#18]
There is no contributing guidelines file in this repository..
i wanna create this .md file , can u assign me with this issue under SWOC 24

**Comment by Nyayabrata01** [comment]
> There is no contributing guidelines file in this repository.. i wanna create this .md file , can u assign me with this issue under SWO

> There is no contributing guidelines file in this repository.. i wanna create this .md file , can u assign me with this issue under SWOC 24

yehh sure !!
go ahead .....
